# Generated by Django 4.0.6 on 2022-12-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_xp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_coins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
