# Generated by Django 4.0.6 on 2022-12-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_user_xp_alter_user_user_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_xp',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
